enum SystemImageMapping {
  static func getIconName(from systemImageName: String) -> String {
    #if SKIP
      switch systemImageName {
      case "arrow.clockwise.circle": return "Icons.Outlined.Refresh"
      case "arrow.forward": return "Icons.Outlined.ArrowForward"
      case "arrow.forward.square": return "Icons.Outlined.ExitToApp"
      case "arrow.left": return "Icons.Outlined.ArrowBack"
      case "arrowtriangle.down.fill": return "Icons.Outlined.ArrowDropDown"
      case "bell": return "Icons.Outlined.Notifications"
      case "bell.fill": return "Icons.Filled.Notifications"
      case "calendar": return "Icons.Outlined.DateRange"
      case "cart": return "Icons.Outlined.ShoppingCart"
      case "cart.fill": return "Icons.Filled.ShoppingCart"
      case "checkmark": return "Icons.Outlined.Check"
      case "checkmark.circle": return "Icons.Outlined.CheckCircle"
      case "checkmark.circle.fill": return "Icons.Filled.CheckCircle"
      case "chevron.down": return "Icons.Outlined.KeyboardArrowDown"
      case "chevron.left": return "Icons.Outlined.KeyboardArrowLeft"
      case "chevron.right": return "Icons.Outlined.KeyboardArrowRight"
      case "chevron.up": return "Icons.Outlined.KeyboardArrowUp"
      case "ellipsis": return "Icons.Outlined.MoreVert"
      case "envelope": return "Icons.Outlined.Email"
      case "envelope.fill": return "Icons.Filled.Email"
      case "exclamationmark.triangle": return "Icons.Outlined.Warning"
      case "exclamationmark.triangle.fill": return "Icons.Filled.Warning"
      case "face.smiling": return "Icons.Outlined.Face"
      case "gearshape": return "Icons.Outlined.Settings"
      case "gearshape.fill": return "Icons.Filled.Settings"
      case "hand.thumbsup": return "Icons.Outlined.ThumbUp"
      case "hand.thumbsup.fill": return "Icons.Filled.ThumbUp"
      case "heart": return "Icons.Outlined.FavoriteBorder"
      case "heart.fill": return "Icons.Outlined.Favorite"
      case "house": return "Icons.Outlined.Home"
      case "house.fill": return "Icons.Filled.Home"
      case "info.circle": return "Icons.Outlined.Info"
      case "info.circle.fill": return "Icons.Filled.Info"
      case "line.3.horizontal": return "Icons.Outlined.Menu"
      case "list.bullet": return "Icons.Outlined.List"
      case "location": return "Icons.Outlined.LocationOn"
      case "location.fill": return "Icons.Filled.LocationOn"
      case "lock": return "Icons.Outlined.Lock"
      case "lock.fill": return "Icons.Filled.Lock"
      case "magnifyingglass": return "Icons.Outlined.Search"
      case "mappin.circle": return "Icons.Outlined.Place"
      case "mappin.circle.fill": return "Icons.Filled.Place"
      case "paperplane": return "Icons.Outlined.Send"
      case "paperplane.fill": return "Icons.Filled.Send"
      case "pencil": return "Icons.Outlined.Create"
      case "person": return "Icons.Outlined.Person"
      case "person.crop.circle": return "Icons.Outlined.AccountCircle"
      case "person.crop.circle.fill": return "Icons.Filled.AccountCircle"
      case "person.crop.square": return "Icons.Outlined.AccountBox"
      case "person.crop.square.fill": return "Icons.Filled.AccountBox"
      case "person.fill": return "Icons.Filled.Person"
      case "phone": return "Icons.Outlined.Call"
      case "phone.fill": return "Icons.Filled.Call"
      case "play": return "Icons.Outlined.PlayArrow"
      case "play.fill": return "Icons.Filled.PlayArrow"
      case "plus": return "Icons.Outlined.Add"
      case "plus.circle.fill": return "Icons.Outlined.AddCircle"
      case "square.and.arrow.up": return "Icons.Outlined.Share"
      case "square.and.arrow.up.fill": return "Icons.Filled.Share"
      case "star": return "Icons.Outlined.Star"
      case "star.fill": return "Icons.Filled.Star"
      case "trash": return "Icons.Outlined.Delete"
      case "trash.fill": return "Icons.Filled.Delete"
      case "wrench": return "Icons.Outlined.Build"
      case "wrench.fill": return "Icons.Filled.Build"
      case "xmark": return "Icons.Outlined.Clear"
      default: return systemImageName
      }
    #else
      return systemImageName
    #endif
  }
}
